# Generated by Django 5.0.6 on 2024-05-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
