# Generated by Django 5.0.6 on 2024-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_app', '0003_doc_name_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='filepath',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
