# Generated by Django 5.0.6 on 2024-05-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_app', '0004_alter_doc_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='notion_app.project'),
        ),
    ]
