# Generated by Django 5.0.6 on 2024-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_app', '0005_alter_doc_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='filepath',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(default='doc', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='project', max_length=255),
        ),
    ]
